apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-06-23T11:08:14Z"
  name: busyapp-debug
  namespace: dev
  resourceVersion: "17669"
  uid: bb74ee48-42f8-4d15-a75d-49b3a48851fa
spec:
  containers:
  - command:
    - sh
    image: busybox
    imagePullPolicy: Always
    name: busyapp
    resources: {}
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6s4qd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-6s4qd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-23T11:08:14Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-23T11:08:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-23T11:08:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-23T11:08:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://44b46fb0cc5a9ee21ad6949b754410b07877f723edc30d1c4ebb72399e004f7d
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:6e494387c901caf429c1bf77bd92fb82b33a68c0e19f6d1aa6a3ac8d27a7049d
    lastState:
      terminated:
        containerID: docker://47c5f36c7aa6e8f5978955451f0d667e144a7d717fe0d8af7903ecbe51c37403
        exitCode: 0
        finishedAt: "2023-06-23T11:08:23Z"
        reason: Completed
        startedAt: "2023-06-23T11:08:16Z"
    name: busyapp
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2023-06-23T11:08:26Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.3.17
  podIPs:
  - ip: 10.1.3.17
  qosClass: BestEffort
  startTime: "2023-06-23T11:08:14Z"
